#index:
#    path: /
#    controller: App\Controller\DefaultController::index

weather_in_city:
  path: /weather/{country}/{city}
  controller: App\Controller\WeatherController:cityAction
  requirements:
    country: "^[A-Z]{2}"
    city: "^[a-zA-Z]{1,25}$"

